[tool.poetry]
name = "rachel-ai"
version = "0.1.0"
description = "Script Collection for the Rachel AI project."
authors = ["Tim Ullrich <[REDACTED_EMAIL]>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.8"
openai = "^1.50.2"
python-dotenv = "^1.0.1"
torch = "2.2.2"
openai-whisper = "^20240930"
sounddevice = "^0.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
